### ISSUE TITLE
Could not HEAD 'https://maven-other.tuya.com/repository/maven-snapshots/com/jakewharton/butterknife-compiler/8.8.1/butterknife-compiler-8.8.1.pom'. Received status code 400 from server: Repository version policy: SNAPSHOT does not allow version: 8.8.1

### ISSUE THREAD

**Issue by honyarAndroid** [TuyaInc/tuyasmart_camera_panel_android_sdk#3]
git clone 源码后，点击运行就报错

Could not HEAD 'https://maven-other.tuya.com/repository/maven-snapshots/com/jakewharton/butterknife-compiler/8.8.1/butterknife-compiler-8.8.1.pom'. Received status code 400 from server: Repository version policy: SNAPSHOT does not allow version: 8.8.1

**Comment by TuyaRockSugar** [comment]
参考github集成：https://github.com/JakeWharton/butterknife/tree/8.8.1，添加对应的仓库
